Cloud testapp
Otus-DevOps-2020-02/altynbai_infra pull request #4
Opened 2020-03-25 09:01 UTC by altynbai

# Выполнено ДЗ №

 - [ ] Основное ДЗ
# Выполнено ДЗ №4

 - [+ ] Основное ДЗ
 - [ ] Задание со *

## В процессе сделано:
1. Установил gcloud на локальный ПК
2. Создал инстансе через утилиту gcloud
3. Установил на инстансе ruby и mongodb
4. Запустил mongodb
5. Задеплоил тестовое приложение и запустил
6. Созданы скрипты install_ruby.sh, install_mongodb.sh и deploy.sh

testapp_IP = 35.242.242.148
testapp_port = 9292
## Как запустить проект:
 
## Как проверить работоспособность:
http://35.242.242.148:9292/ 

## PR checklist
 - [+ ] Выставил label с номером домашнего задания
 - [+] Выставил label с темой домашнего задания

2020-03-25 19:14 UTC, mrgreyves requested changes
Здравствуйте!) К сожалению тесты красные. Оставил комментарий к файлу. Вовзвращаю на доработку.

2020-03-25 19:14 UTC, mrgreyves commented on install_mongodb.sh
> +#!/bin/bash
Нужно перепроверить этот скрипт установки монги =)

2020-03-27 05:55 UTC, mrgreyves requested changes
Здравствуйте! Оставил комментарий к файлу, возвращаю на доработку.

2020-03-27 05:55 UTC, mrgreyves commented on install_mongodb.sh
> +#!/bin/bash
Возвращаемся к перепроверке скрипта. Конструкция с использованием bash тут не нужна, к тому же она оформлена не правильно.

2020-03-28 13:04 UTC, mrgreyves requested changes
Здравствуйте!) У вас проблемы с тестами. Разъяснение по монге я дал в общем канале слака, нужно исправить. ДЗ возвращаю на доработку.

2020-03-28 18:33 UTC, altynbai commented
> Здравствуйте!) У вас проблемы с тестами. Разъяснение по монге я дал в общем канале слака, нужно исправить. ДЗ возвращаю на доработку.

Сделал все заново. Также не проходит тесты. Сам сервис работает http://35.242.242.148:9292.
Во вложениии скриншот портов на инстансе. Вроде все работает. 
![Screenshot from 2020-03-29 00-32-06](https://user-images.githubusercontent.com/11902104/77830733-c4225f80-7154-11ea-88e5-954e3136ebbd.png)

2020-03-29 15:15 UTC, mrgreyves requested changes
Здравствуйте!) Скрипт который вы положили в репозиторий, и который должен устанавливать mongo не рабочий чуть больше чем полность. Уберите из него bash -c или экранируйте команды.

2020-03-30 09:16 UTC, mrgreyves approved these changes
Здравствуйте!) Апрув!)

2020-04-06 19:31 UTC, merged